### ISSUE TITLE
run dev error

### ISSUE THREAD

**Issue by jarnohenneman** [workco/marvin#70] opened 2018-02-10 07:35 UTC
Downloaded the source;

npm install
npm run

ERROR in ./client.js
Module build failed: SyntaxError: Unexpected token (22:2)

```
21 | renderMethod(
22 |   <AppContainer>
   |   ^
23 |     <Provider store={ store }>
24 |       <BrowserRouter>
25 |         <App />

```

debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/8.9.1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'client:build' ]
2 info using npm@5.6.0
3 info using node@v8.9.1
4 verbose run-script [ 'preclient:build', 'client:build', 'postclient:build' ]
5 info lifecycle marvin@1.0.0~preclient:build: marvin@1.0.0
6 info lifecycle marvin@1.0.0~client:build: marvin@1.0.0
7 verbose lifecycle marvin@1.0.0~client:build: unsafe-perm in lifecycle true
8 verbose lifecycle marvin@1.0.0~client:build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/jarnohenneman/Projects/marvin/node_modules/.bin:/Users/jarnohenneman/.rbenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle marvin@1.0.0~client:build: CWD: /Users/jarnohenneman/Projects/marvin
10 silly lifecycle marvin@1.0.0~client:build: Args: [ '-c',
10 silly lifecycle   'npm run clean && cross-env NODE_ENV="production" webpack' ]
11 silly lifecycle marvin@1.0.0~client:build: Returned: code: 2  signal: null
12 info lifecycle marvin@1.0.0~client:build: Failed to exec client:build script
13 verbose stack Error: marvin@1.0.0 client:build: `npm run clean && cross-env NODE_ENV="production" webpack`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid marvin@1.0.0
15 verbose cwd /Users/jarnohenneman/Projects/marvin
16 verbose Darwin 17.3.0
17 verbose argv "/usr/local/Cellar/node/8.9.1/bin/node" "/usr/local/bin/npm" "run" "client:build"
18 verbose node v8.9.1
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 2
22 error marvin@1.0.0 client:build: `npm run clean && cross-env NODE_ENV="production" webpack`
22 error Exit status 2
23 error Failed at the marvin@1.0.0 client:build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]

**Comment by Stanko** [comment] 2018-02-10 08:12
Hello @jarnohenneman,
You probably downloaded a zip, and when unzipped, you haven't copied hidden files including .babelrc and other config files. Without babel configuration webpack can't handle JSX files.

Duplicate of https://github.com/workco/marvin/issues/69 and few others.

**Closed by Stanko** 2018-02-10 08:12 UTC
Labels: duplicate
